

server:
  port: 8010


#????????????????
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

    url: jdbc:mysql://192.168.1.3:3306/product_qiyue
    username: root
    password: 213316



  data:
    mongodb:
      uri: mongodb://192.168.1.3:27017/product_qiyue


  #????dubbo????????:???????????????


mybatis:
  #mybatisxml???????
  mapper-locations: classpath:mapper/*.xml
  #showsql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

java4all:
  file:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyid: LTAI4Fk1RSuTxvoixXsFnaj4
    keysecret: e53NCciGE2JKwIeC2JqzDamEKGGzrv
    bucketname1: cold
    filehost: img

