server:
  port: 8010


#????????????????
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

    url: jdbc:mysql://192.168.1.3:3306/product_qiyue
    username: root
    password: 213316

  redis:
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
    cluster:
      nodes: 192.168.252.128:7000,192.168.252.128:7001,192.168.252.128:7002,192.168.252.128:7003,192.168.252.128:7004,192.168.252.128:7005


  data:
    mongodb:
      uri: mongodb://192.168.1.3:27017/product_qiyue


  #????dubbo????????:???????????????


mybatis:
  #mybatisxml???????
  mapper-locations: classpath:mapper/*.xml
  #showsql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

java4all:
  file:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyid: LTAI4Fk1RSuTxvoixXsFnaj4
    keysecret: e53NCciGE2JKwIeC2JqzDamEKGGzrv
    bucketname1: cold
    filehost: img